### ISSUE TITLE
Cards are not respecting the limit

### ISSUE THREAD

**Issue by cjdduarte** [lovac42/HoochieBaby#3]
I have the following steps: 25 1440.

When I forget the card, it is expected to return in 25 minutes.
Even with randomness, I understand that this limit defined in the steps should be respected.
I noticed that the card returns almost immediately when I forget it (after 3 or 5 cards responded).
Is it really wrong or is it a purposeful implementation?

**Comment by lovac42** [comment]
To add randomness, it will respect the limit within Learn ahead limit. Do you have a large value set for "Learn ahead limit" in preferences? Try setting it to 1-5 mins.

**Comment by cjdduarte** [comment]
is set to 30 minutes.
I'll change and do the tests again.

**Comment by cjdduarte** [comment]
Work
