### ISSUE TITLE
doubt:

### ISSUE THREAD

**Issue by cjdduarte** [lovac42/HoochieBaby#5]
1) What is the difference between these two options? There are three addons (Mama, Papa and Bebe) Why are they just two options? I did not understand correctly.

2) What happens in not using them?

![image](https://user-images.githubusercontent.com/42243532/51672023-a0dcad00-1fb1-11e9-8e5c-11b2436a55bd.png)

**Comment by lovac42** [comment]
1. One sorts day learning queue, one sorts review queue. You can't sort the new queue, there's no data to sort.

2. Default is None or randomized.

**Comment by lovac42** [comment]
If you use these addons:
https://ankiweb.net/shared/info/4241959
or
https://ankiweb.net/shared/info/1008566916

You can see how the cards are being sorted. If you sort by due, the due will grow bigger after each card. Each addon is separate, they have separate config options. The sort for hoochie mama will not affect hoochie baby.

Also Hoochie mama is the V2 scheduler. If you're on V2 and you're not using the sort features, you don't need hoochie mama at all.
