### ISSUE TITLE
Question on settings

### ISSUE THREAD

**Issue by Z1839** [lovac42/HoochieBaby#6]
Hello,
I love your Hoochie addons, they're a game changer. I just have a question regarding the settings on HoochieBaby. I was wondering what the difference between the "Randomize DayLrnQ" and "DayLrnQ+QController" settings.

**Comment by lovac42** [comment]
QController randomize all review Q. Anki default is lrn, review, day-lrn, new, all remaining lrn items in that order. This randomizes all that in no given order.

**Comment by Z1839** [comment]
Awesome! Wow, that makes me love the addon even more. So if I just have randomize day learnQ and not Qcontroller, it just randomizes whatever stage I’m in (so random Lrn, random review, etc. in Anki’s default order?)

**Comment by lovac42** [comment]
Yup, it uses anki's default QController.

Randomizing QController actually makes learning harder, some people like it for testing or cramming, but I didn't like it as I tried it. It makes learning/memorizing harder.
