### ISSUE TITLE
Preferences not being reflected in Queue

### ISSUE THREAD

**Issue by penguingiraffe2** [lovac42/HoochieBaby#7]
I've set my preferences like so 

![image](https://user-images.githubusercontent.com/18012559/56051505-d83f3800-5d1c-11e9-9e2d-6e8baf96af4a.png)

However, when going through review cards and comparing to Lapse data, I am seeing cards with Lapse of 0 before cards that have Lapse of 3, 2, 1. 

Is it because these cards are overdue that it is not working properly?

**Comment by lovac42** [comment]
It sounds like they are intra-day learning cards and not day-learning cards. HoochieBaby only affects Day-Learning cards. Intra-Day learning cards are **time sensitive** and scheduled by Anki.
