### ISSUE TITLE
Sort by starting ease

### ISSUE THREAD

**Issue by galantra** [lovac42/HoochieBaby#8]
I combine HoochieBaby with Knockout deck.

Does "sort by ease" in HoochieBaby sort the new cards by starting ease of the deck? Or do new cards have same ease value, and therefore are totally randomized?

If randomization is the case, I would like to suggest to include starting ease (from the corresponding deck options). I'm not sure whether it's possible, since knockout deck uses only one deck's options for all, as I understand it.

**Comment by lovac42** [comment]
Sort by ease sorts the cards's current ease factor, "starting ease" is something else not related to reviews. This will require a full page essay to explain... so I'm not going to. You will learn it as you use Anki more.
